### ISSUE TITLE
Documentation unclear/incomplete

### ISSUE THREAD

**Issue by andreas-p** [jkroepke/openvpn-auth-oauth2#149]
### Current Behavior

Reviewing the configuration file section of the documentation, I found:
```
http:
  tls: true
  key: <keyfile>
  cert: <certfile>
openvpn:
  bypass:
    commonnames: ""
oauth2:
  validate:
    commonname: ""
    roles: ""
```
- TLS configuration works fine for me, section missing 
- Both commonname options appear surprising to me, since the command line options are `--openvpn.bypass.cn` and `--oauth2.validate.common-name`
- Wondering about oauth2.validate.roles: is a single role checked, or multiple, if multiple is the string comma or space separated, or maybe list of strings?

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):
- OIDC Provider:
