### ISSUE TITLE
v1.16.0-rc.2: openvpn-auth-oauth2.service: Failed with result 'core-dump'.

### ISSUE THREAD

**Issue by jkroepke** [jkroepke/openvpn-auth-oauth2#172]
@jkroepke I was already trying that yesterday, while refactoring my installation script to incorporate the ownership changes. So **I do expect my current setup to fail**, but I no longer get any details why it's failing in the new setup. Journalcl output:
```
Feb 14 11:24:28 shared-hub-vpn-gateway systemd[1]: Started OpenVPN authenticator.
░░ Subject: A start job for unit openvpn-auth-oauth2.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit openvpn-auth-oauth2.service has finished successfully.
░░ 
░░ The job identifier is 871563.
Feb 14 11:24:28 shared-hub-vpn-gateway systemd[1]: openvpn-auth-oauth2.service: Main process exited, code=dumped, status=31/SYS
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit openvpn-auth-oauth2.service has exited.
░░ 
░░ The process' exit code is 'dumped' and its exit status is 31.
Feb 14 11:24:28 shared-hub-vpn-gateway systemd[1]: openvpn-auth-oauth2.service: Failed with result 'core-dump'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit openvpn-auth-oauth2.service has entered the 'failed' state with result 'core-dump'.
```
I have to add: I also did try to change from the `/etc/sysconfig/openvpn-auth-oauth2` file to `/etc/openvpn-auth-oauth2/config.yaml`

config.yaml
```
-rw-r-----   1 root openvpn-auth-oauth2  851 Feb 14 11:25 config.yaml
```
```
log:
  format: console
  level: INFO
http:
  baseurl: "https://xx:9000"
  cert: "/etc/openvpn-auth-oauth2/fullchain.pem"
  key: "/etc/openvpn-auth-oauth2/privkey.pem"
  listen: ":9000"
  secret: "xx"
  tls: true
openvpn:
  addr: "unix:///run/openvpn/server.sock"
  password: "xx"
oauth2:
  issuer: "https://accounts.google.com"
  client:
    id: "xx"
    secret: "xx"
  validate:
    groups:
      - xx-admin
      - xx-developer
  refresh:
    enabled: true
    expires: 8h0m0s
    secret: "xx"
provider:
  google:
    admin-email: "xx"
    service-account-config: "file:///etc/openvpn-auth-oauth2/sa.json"
```

/etc/sysconfig/openvpn-auth-oauth2
```
# This file is sourced by the openvpn-auth-oauth2.service

# CONFIG_FILE is the path to the configuration file and used in the systemd service file only.
CONFIG_FILE=/etc/openvpn-auth-oauth2/config.yaml
```

Please let me know how I can see errors/misconfigurations in your component again

_Originally posted by @Pionerd in https://github.com/jkroepke/openvpn-auth-oauth2/issues/168#issuecomment-1943585219_
