### ISSUE TITLE
v1.16.0-rc.2: provider `google` not recognised in client.yaml

### ISSUE THREAD

**Issue by Pionerd** [jkroepke/openvpn-auth-oauth2#173]
### Current Behavior

Previously, I used `CONFIG_OAUTH2_PROVIDER=google` in `/etc/sysconfig/openvpn-auth-oauth`.

My current `config.yaml` includes:
```
provider:
  google:
    admin-email: "googlecloudidentity@pionative.com"
    service-account-config: "file:///etc/openvpn-auth-oauth2/sa.json"
```

but the logs show:
```
xx@xx:/etc/systemd/system$ sudo /usr/bin/openvpn-auth-oauth2 --config /etc/openvpn-auth-oauth2/config.yaml
time=2024-02-14T11:41:33.689Z level=INFO msg="discover oidc auto configuration with provider **generic** for issuer https://accounts.google.com"
```

Leads to similar errors as before when authentication without `CONFIG_OAUTH2_PROVIDER=google`: 
```
Some requested scopes were invalid. {valid=[openid, https://www.googleapis.com/auth/userinfo.profile], invalid=[offline_access]} 
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):
- OIDC Provider:
