### ISSUE TITLE
Failed to exchange token: parsing of request failed: token contains an invalid number of segments 

### ISSUE THREAD

**Issue by cdalamagkas** [jkroepke/openvpn-auth-oauth2#344]
### Problem Statement

I am trying to integrate the OpenVPN server of pfSense with my self-hosted Authentik. An Oauth2/OpenID provider has been created on authentik. In the provider's option, for signing and encrypting the tokens, a self-signed CA has been selected, which has been imported to pfSense' FreeBSD and is trusted.

When I am trying to connect via VPN:
1. a new tab opens on my browser.
2. I provide my credentials to Authentik login portal and click login
3. Login is successful and I am redirected to the baseUrl of openvpn-auth-oauth2 (https://vpn.XXX.gr/oauth2/callback?code) 
4. The page of openvpn-auth-oauth2 shows the "Access denied" message. Also, the `openvpn-auth-oauth2` logs indicate the following error: `Unauthorized: failed to exchange token: parsing of request failed: token contains an invalid number of segments`.

Here is a JWT payload sample of Authentik:
```json
{
    "iss": "https://auth.XXX.gr/application/o/openvpn-auth-oauth2/",
    "sub": "XXX",
    "aud": "XXX",
    "exp": 1731024945,
    "iat": 1731023145,
    "auth_time": 1731023145,
    "acr": "goauthentik.io/providers/oauth2/default",
    "email": "XXX",
    "email_verified": true,
    "name": "XXX",
    "given_name": "XXX",
    "preferred_username": "cdalamagkas",
    "nickname": "cdalamagkas",
    "groups": [
        "XXX",
        "XXX",
        "users"
    ]
}
```
I am not sure whether something is wrong with Authentik's token, since I have sucesfully integrated Authentik with Proxmox and Portainer.

The JWKS endpoint of Authentik return the following algorithms: `RS256`, `RSA-OAEP-256`.

Here is my `config.yml` that the `openvpn-auth-oauth2` process reads:
```yml
debug:
  pprof: false
  listen: ":9001"
http:
  baseurl: "https://vpn.XXX.gr/"
  enable-proxy-headers: true
  listen: "192.168.XXX.1:9000"
  secret: "XXX"
  tls: false
log:
  format: console
  level: INFO
  vpn-client-ip: true
oauth2:
  client:
    id: "XXX"
    secret: "XXX"
  issuer: "https://auth.XXX.gr/application/o/openvpn-auth-oauth2/"
  validate:
    common-name: "preferred_username"
    common-name-case-sensitive: false
    ipaddr: false
    issuer: true
  nonce: false
  pkce: false
  refresh:
    enabled: false
    expires: 8h0m0s
    use-session-id: false
    validate-user: true
openvpn:
  addr: "unix:///var/run/openvpn_server2.sock"
  password: "XXX"
  auth-token-user: false
  auth-pending-timeout: 2m
  common-name:
    environment-variable-name: common_name
    mode: plain
  pass-through:
    address: "unix:///run/openvpn/pass-through.sock"
    enabled: false
```

And the OpenVPN config:
```
management /var/run/openvpn_server2.sock unix /etc/openvpn-auth-oauth2/password.txt;
management-client-auth;
auth-user-pass-optional;
auth-gen-token 28800 external-auth;
```

### openvpn-auth-oauth2 logs

```shell
time=2024-11-08T01:19:23.349+02:00 level=INFO msg="discover oidc auto configuration with provider generic for issuer https://auth.XXX.gr/application/o/openvpn-auth-oauth2/"
time=2024-11-08T01:19:23.571+02:00 level=INFO msg="connect to openvpn management interface unix:///var/run/openvpn_server2.sock"
time=2024-11-08T01:19:23.572+02:00 level=INFO msg="openvpn-auth-oauth2 started with base url https://vpn.XXX.gr/"
time=2024-11-08T01:19:23.572+02:00 level=INFO msg="start HTTP server listener on 192.168.XX.1:9000"
time=2024-11-08T01:19:23.572+02:00 level=INFO msg="connection to OpenVPN management interface established."
time=2024-11-08T01:19:23.572+02:00 level=INFO msg="OpenVPN Version: OpenVPN 2.6.8 amd64-portbld-freebsd14.0 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [MH/RECVDA] [AEAD] [DCO] - Management Version:5"
time=2024-11-08T01:19:40.603+02:00 level=INFO msg="new client connection" ip=XXX:56992 cid=12 kid=1 common_name=cdalamagkas reason=CONNECT session_id=cxWhINIlXQomupir session_state=Initial
time=2024-11-08T01:19:40.603+02:00 level=INFO msg="start pending auth" ip=XXX:56992 cid=12 kid=1 common_name=cdalamagkas reason=CONNECT session_id=cxWhINIlXQomupir session_state=Initial
time=2024-11-08T01:19:40.713+02:00 level=INFO msg="initialize authorization via oauth2" ip=XXX:56992 cid=12 kid=1 common_name=cdalamagkas
time=2024-11-08T01:19:44.333+02:00 level=INFO msg="deny OpenVPN client cid 12, kid 1" ip=XXX:56992 cid=12 kid=1 common_name=cdalamagkas
time=2024-11-08T01:19:44.333+02:00 level=WARN msg="Unauthorized: failed to exchange token: parsing of request failed: token contains an invalid number of segments" ip=XXX:56992 cid=12 kid=1 common_name=cdalamagkas error_id=9be9fbae59df1400bc931500d8cac65ff8936369e025c29a9b79c579a95a009f
time=2024-11-08T01:19:52.021+02:00 level=INFO msg="client disconnected" ip=: cid=12 common_name="" reason=DISCONNECT session_id="" session_state=""
time=2024-11-08T01:19:52.021+02:00 level=WARN msg="error from token store: value does not exist" ip=: cid=12 common_name="" reason=DISCONNECT session_id="" session_state=""
```

### Environment

- openvpn-auth-oauth2 Version: 1.22.2
- OpenVPN Server Version: 2.6.8
- Server OS: pfSense (FreeBSD)
- OpenVPN Client (flavor, OS): OpenVPN 2.6.12 [git:v2.6.12/038a94bae57a446c], Windows 11

**Comment by jkroepke** [comment]
I guess token encryption is not supported

**Comment by cdalamagkas** [comment]
Yes, after turning off token encryption, the authentication flow worked! I thought that I already tried this, I don't understand how it works now. Maybe I was changing various configurations in the meantime.. I also activated the `nonce` and `pkce` options, and still works.

This is my final config, for anyone who might be interested: 

```yml
debug:
  pprof: false
  listen: ":9001"
http:
  baseurl: "https://vpn.XXX.gr/"
  enable-proxy-headers: true
  listen: "192.168.XX.1:9000"
  secret: "XXX"
  tls: false
log:
  format: console
  level: INFO
  vpn-client-ip: true
oauth2:
  client:
    id: "XXX"
    secret: "XXX"
  issuer: "https://auth.XXX.gr/application/o/openvpn-auth-oauth2/"
  validate:
    common-name: "preferred_username"
    common-name-case-sensitive: false
    ipaddr: false
    issuer: true
  nonce: true
  pkce: true
  refresh:
    enabled: false
    expires: 8h0m0s
    use-session-id: false
    validate-user: true
openvpn:
  addr: "unix:///var/etc/openvpn/server1/sock"
  auth-token-user: false
  auth-pending-timeout: 2m
  bypass:
    common-names: "XXX"
  common-name:
    environment-variable-name: common_name
    mode: plain
```

Also, in the OpenVPN server config, I removed the `management` directive, since pfSense already configures a management socket by default (without password authentication though). 

It would be great considering the development of a pfSense package that provides openvpn-auth-oauth2. In case you consider this, the only limitation is that the pfSense dashboard cannot use the OpenVPN socket at the same time with openvpn-auth-oauth2. So, when you are running openvpn-auth-oauth2, you cannot see the connected VPN clients from the pfSense dashboard.

Thank you for your time!
